openapi: 3.0.3
info:
  title: Mosquito
  description: 'Mosquito - A lightweight task api'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/tasks/overdue:
    get:
      summary: 'Shows all tasks that are overdue.'
      operationId: showsAllTasksThatAreOverdue
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/tasks:
    get:
      summary: 'List all tasks.'
      operationId: listAllTasks
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created task in the backend.'
      operationId: storeANewlyCreatedTaskInTheBackend
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: ukzsajwyjplogosoupx
                description:
                  type: string
                  description: ''
                  example: ratione
                state:
                  type: string
                  description: ''
                  example: todo
                  enum:
                    - todo
                deadline:
                  type: string
                  description: 'Must be a valid date. Must be a date after <code>today</code>.'
                  example: '2064-09-16'
                project_id:
                  type: string
                  description: ''
                  example: null
              required:
                - title
                - description
                - state
                - deadline
      security: []
  '/api/v1/tasks/{id}':
    get:
      summary: 'Display a specific task owned by the current user.'
      operationId: displayASpecificTaskOwnedByTheCurrentUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update a specific task for the current user.'
      operationId: updateASpecificTaskForTheCurrentUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: btg
                description:
                  type: string
                  description: ''
                  example: minima
                state:
                  type: string
                  description: ''
                  example: done
                  enum:
                    - in_progress
                    - done
                project_id:
                  type: string
                  description: ''
                  example: null
                deadline:
                  type: string
                  description: 'Must be a valid date. Must be a date after <code>today</code>.'
                  example: '2094-10-23'
              required:
                - title
                - description
                - state
                - deadline
      security: []
    delete:
      summary: 'Remove a specified task for the current user.'
      operationId: removeASpecifiedTaskForTheCurrentUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the task.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/v1/tasks/{task_id}/project':
    get:
      summary: 'Show projects that are associated with a task.'
      operationId: showProjectsThatAreAssociatedWithATask
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: task_id
        description: 'The ID of the task.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/v1/tasks/{task_id}/deadline':
    patch:
      summary: 'Update the deadline of a task.'
      operationId: updateTheDeadlineOfATask
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                deadline:
                  type: string
                  description: 'Must be a valid date. Must be a date after <code>today</code>.'
                  example: '2061-08-27'
              required:
                - deadline
      security: []
    parameters:
      -
        in: path
        name: task_id
        description: 'The ID of the task.'
        example: 1
        required: true
        schema:
          type: integer
  /api/v1/projects:
    get:
      summary: 'List all projects.'
      operationId: listAllProjects
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/v1/projects/{id}':
    get:
      summary: 'Show a specific project.'
      operationId: showASpecificProject
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update a specific project.'
      operationId: updateASpecificProject
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: odvseulixkmgjusfklezhigb
              required:
                - title
      security: []
    delete:
      summary: 'Remove a project.'
      operationId: removeAProject
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the project.'
        example: 1
        required: true
        schema:
          type: integer
  /api/v1/project:
    post:
      summary: 'Store a newly created project in the backend.'
      operationId: storeANewlyCreatedProjectInTheBackend
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: yaya
              required:
                - title
      security: []
  '/api/v1/projects/{project_id}/tasks':
    get:
      summary: 'Show a project with its associacted tasks.'
      operationId: showAProjectWithItsAssociactedTasks
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: project_id
        description: 'The ID of the project.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/v1/users/{user_id}/tasks':
    get:
      summary: 'Show a user with his associated tasks.'
      operationId: showAUserWithHisAssociatedTasks
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: user_id
        description: 'The ID of the user.'
        example: 1
        required: true
        schema:
          type: integer
  /api/login:
    post:
      summary: 'Log in an user.'
      operationId: logInAnUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: oschuppe@example.net
                password:
                  type: string
                  description: ''
                  example: ut
              required:
                - email
                - password
      security: []
tags:
  -
    name: Endpoints
    description: ''
